name: 'Test Suite'
description: 'Run build and unit tests'
outputs:
  build_result: # exit status
    description: 'The exit status of the last executed command'
    value: ${{ steps.tests.outputs.build_result }}
runs:
  using: 'composite'
  steps:
    - id: tests
      run: ./execute_tests.sh
      shell: bash
